# version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dls-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: dls-postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-dlsuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dlspassword}
      POSTGRES_DB: ${DB_NAME:-distributed_logs}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-dlsuser} -d ${DB_NAME:-distributed_logs}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  pg-data:
    driver: local
